# Generated by Django 2.2 on 2020-01-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=32, verbose_name='省')),
                ('city', models.CharField(max_length=32, verbose_name='市')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='地址')),
                ('source', models.TextField(blank=True, default=None, null=True, verbose_name='数据来源')),
                ('verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='所在地')),
                ('verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('main_text', models.DateTimeField(auto_now=True, verbose_name='正文')),
            ],
            options={
                'verbose_name': '(爱心)团体',
                'verbose_name_plural': '(爱心)团体',
            },
        ),
        migrations.CreateModel(
            name='TeamContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='称呼')),
                ('phone', models.CharField(max_length=31, verbose_name='手机')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '团体(捐赠)联系人',
                'verbose_name_plural': '团体(捐赠)联系人',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='物品名')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('amount', models.IntegerField(default=-1, verbose_name='需求数量')),
                ('receive_amount', models.IntegerField(default=0, verbose_name='收到数量')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '机构需求',
                'verbose_name_plural': '机构需求',
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='称呼')),
                ('phone', models.CharField(max_length=31, verbose_name='手机')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '机构联系人',
                'verbose_name_plural': '机构联系人',
            },
        ),
    ]
