# Generated by Django 2.2 on 2020-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdemand',
            name='remark',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
