# Generated by Django 2.2 on 2020-01-31 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200131_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inspector',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='是否是手动添加'),
        ),
        migrations.AddField(
            model_name='team',
            name='inspector',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
            preserve_default=False,
        ),
    ]
