# Generated by Django 2.2 on 2020-01-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200131_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='emergency',
            field=models.IntegerField(default=0, verbose_name='紧急程度'),
        ),
    ]
