# Generated by Django 2.2 on 2020-02-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organization_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='main_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='正文'),
        ),
    ]
