# Generated by Django 2.2 on 2020-02-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_team_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('charity', '慈善机构/公益组织'), ('company', '公司/机构'), ('student', '学生组织'), ('other', '其它')], default='charity', max_length=128, verbose_name='团队类型'),
        ),
    ]
