# Generated by Django 2.2 on 2020-02-05 16:07

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('api', '0006_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='wechat_qrcode',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wechat_qrcode_team', to=settings.FILER_IMAGE_MODEL, verbose_name='微信二维码'),
        ),
    ]
